# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for app

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'RCTLinkingIOS',
    'RCTImage'
  ]

  pod 'yoga',
    :path => "../node_modules/react-native/ReactCommon/yoga",
    :inhibit_warnings => true

    
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'


  pod 'react-native-aes', :path => '../node_modules/react-native-aes-crypto'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

end

